export const pricingTiers = [
  {
    name: "Basic",
    description: "Perfect for individuals and small projects",
    price: 9,
    period: "month",
    features: [
      "Up to 10 projects",
      "5GB storage",
      "Community support",
      "Basic analytics",
      "99.9% uptime SLA",
    ],
    cta: "Get Started",
    popular: false,
    featured: false,
  },
  {
    name: "Premium",
    description: "Ideal for growing teams and businesses",
    price: 29,
    period: "month",
    features: [
      "Unlimited projects",
      "50GB storage",
      "Priority support",
      "Advanced analytics",
      "99.99% uptime SLA",
      "Custom integrations",
      "API access",
    ],
    cta: "Start Free Trial",
    popular: true,
    featured: true,
  },
  {
    name: "Enterprise",
    description: "For large organizations with custom needs",
    price: 99,
    period: "month",
    features: [
      "Everything in Premium",
      "Unlimited storage",
      "24/7 phone support",
      "Custom analytics",
      "99.999% uptime SLA",
      "Dedicated account manager",
      "SSO & SAML",
      "Custom contracts",
    ],
    cta: "Contact Sales",
    popular: false,
    featured: false,
  },
  {
    name: "Ultimate",
    description: "Maximum power and flexibility",
    price: 299,
    period: "month",
    features: [
      "Everything in Enterprise",
      "White-label solution",
      "On-premise deployment",
      "Custom development",
      "Unlimited API calls",
      "Training & onboarding",
      "Legal review",
    ],
    cta: "Contact Sales",
    popular: false,
    featured: false,
  },
]
